name: emptydirclone-e2e-tests

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

permissions:
  actions: read
  packages: write

jobs:
  build-image:
    uses: ./.github/workflows/image-build-push.yaml
    with:
      directory: emptyDirClone
    secrets: inherit
  e2e-tests:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      -
        name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run tests
        working-directory: ./emptyDirClone
        run: |
          docker pull "ghcr.io/${{ github.repository }}:${{ needs.build-image.outputs.tag }}"
          docker image ls
          kind create cluster --name test --kubeconfig test.yml
          export KUBECONFIG=test.yml
          sleep 10
          kubectl get nodes
          docker tag "ghcr.io/${{ github.repository }}:${{ needs.build-image.outputs.tag }}" "ghcr.io/${{ github.repository }}:debug"
          kind load docker-image "ghcr.io/${{ github.repository }}:debug" --name test
          kind load docker-image "ghcr.io/${{ github.repository }}:${{ needs.build-image.outputs.tag }}" --name test
          make e2e E2E_TEST_ARGS="--fail-fast --v 6 --image-tag ${{ needs.build-image.outputs.tag }}"
      -
        name: Cleanup
        if: always()
        run: |
          for i in $(kind get clusters); do kind delete cluster --name $i; done
