name: emptydirclone-e2e-tests

on:
  workflow_run:
    workflows: [emptydirclone-image-build-push]
    types: [completed]

permissions:
  actions: read

jobs:
  on-success:
    name: Triggered via ${{ github.event.workflow_run.name }}#${{ github.event.workflow_run.run_number }}(${{ github.event.workflow_run.id }})
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download docker tag artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-tags
          path: .docker-tags
          run-id: ${{ github.event.workflow_run.id }}

      - name: Run tests
        run: |
          make e2e E2E_TEST_ARGS="--fail-fast --v 6 --image-tag lalala"
